name: weather_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  http: ^0.13.3
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0




  
  cupertino_icons: ^1.0.6
  bloc: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
